# The proposal
<!--
This is where the proposal should be outlined. 
-->

## Overview
<!--
At a high-level address what your proposal is and how it will address the problem identified. Highlight any benefits to the R Community that follow from solving the problem. This should be your most compelling section.
-->

During the first stage of the work (September 2019 until March 2020),
we developed all features of the `sftrack`, which now provides
foundations to build, handle, summarize, and plot tracking data. As
the package is now ready for use, we will work with R package
developers to help them integrate and adjust `sftrack` solutions into
their data flow (June–August). Secondly, we will use this
collaborative development to establish the version 1.0.0, which
defines the public API. This major stepping stone will be submitted to
to [CRAN](https://cran.r-project.org/) and to
[rOpenSci](https://ropensci.org/).


## Detail
<!--
Go into more detail about the specifics of the project and it delivers against the problem.

Depending on project type the detail section should include:

 - [ ] Minimum Viable Product
 - [ ] Architecture
 - [ ] Assumptions
-->

In the first stage of the work, we defined a precise data model for
tracking data, which recognizes the duality of locations, in the form
of geographic $(x,y,z)$ and temporal $(t)$ coordinates, and steps,
i.e. the straight-line segment connecting two successive locations.
Throughout the process, we have focused on providing solid
documentation of the package and its specifications, targeting both
users and package developers, which is essential for a broad adoption
of the `sftrack` package.  The development of the package happened in
the open on GitHub (https://github.com/mablab/sftrack), where we have
received feedback from the community in the form of use cases
(https://github.com/mablab/sftrack/issues?q=label%3Ause-case).

In the next stage of this project, we will work with developers to
finalize the implementation, to ensure that `sftrack` meets all needs
of the movement community.  We have ongoing discussions with 9
developers of 10 packages, ranging from import of GPX files to animal
movement ecology, through human tracking devices for running, cycling
and swimming. Specific elements that will require further development
or fine-tuning include the grouping structure (coined `burst`, where
the individual identification of the moving object is required, and
can be completed by any number of arbitrary factors) and the error
measure (typically the error in GPS positions), both of which have no
established standard. 

We will work with developers of R tracking package (including, but not
limited to the one mentioned above) to integrate `sftrack` in their
data flow. How we will conduct the work will depend on the role and
complexity of tracking data in each package:

* Input data only (e.g. `crawl` or `spatsoc`): work with the
  developers on their package initial function(s) to make them
  `sftrack`-ready (preferably in addition to the original input
  format).

* Simple data classes (e.g. `amt::track_xy`/`amt::track_xyt`): work
  with the developers to directly replace their classes with the one
  offered by `sftrack`.

* Complex data classes (e.g. `adehabitatLT::ltraj` and
  `trackeR::trackeRdata`): For these packages, the work will be
  conducted in two phases: 1) develop bi-directional converters from
  and to `sftrack` classes (which should be lossless both ways); 2)
  ultimately replace these data classes with the new ones offered by
  `sftrack`.

The second stage of work will entirely be focused on establishing
`sftrack` in the R tracking ecosystem.  We will first prepare the
package for submission to [CRAN](https://cran.r-project.org/), then
focus on the preparation and submission of `sftrack` to
[rOpenSci](https://ropensci.org/). The first step will ensure that the
package stays up-to-date with R and other package dependencies, while
the second step will guarantee that `sftrack` adheres to a best
practice standards for R and reproducible science. Packages submitted
to rOpenSci go through detailed peer-review by other developers—the
rOpenSci certification (through their badge) will assure `sftrack` is
easy to use, well documented, and well coded.
