# Project plan

## Start-up phase (DONE)
<!--
Covering the planning phase, this section should provide a relatively detailed plan of how work will start on the project. This section is important because projects need to get up and running quickly.


 - [ ] Setting up collaboration platform inc. code for contributors etc.
 - [ ] Licence decisions
 - [ ] Reporting framework
-->

The `sftrack` package is meant to be a cornerstone for the development
of a more cohesive movement community in R. The first stage of the
work, which is just finished, has provided solid technical foundations
for tracking data in R. Our project has already been received very
positively on Twitter, which we use to channel our communication. We
explained our approach and decisions in a series of 4 blog posts
(https://mablab.org/tags/sftraj/). We used them to call for feedback
from the community, and received the perspective on `sftrack` from 10
developers of 11 packages (outside of the core team), who expressed
interest in working together. Altogether, the feedback we received
only confirmed the need for a central tracking package in R. We will
keep working in the open, and collect feedback from the whole movement
community.


## Technical delivery
<!--
Covering the actual delivery of the project this section should provide at least a high-level the implementation. 

Including target dates is really important as you need to be committed and the ISC need to have a means of tracking delivery
-->

We will deliver the following products during the 6-month period of
the grant:

* **Submission to CRAN** [month 1]: `sftrack` is currently installable
  from the GitHub repository, and passes all CRAN checks. However,
  publication on CRAN will allow for easy installation on any
  computer, as well as enabling the dependency system of R packages,
  which are both mandatory for broad adoption.  In this first stage,
  we will thus submit the package to CRAN.
* **Data class converters** [month 1–2]: We will provide converters to
  classes from the main tracking packages, such as
  `adehabitatLT::ltraj` and `trackeR::trackeRdata`, integrated into
  `as_sftrack` through method dispatch. We will develop bidirectional
  conversion, and work towards lossless conversion both ways.
  Depending on the specific requirements of other classes, this will
  require adjusting the classes already developed in `sftrack`.
* **Integration of `sftrack`** [month 2–4]: In parallel, we will work
  with developers willing to fully integrate the solution offered by
  `sftrack` into their package data flow. This step may require
  substantial rewriting of other packages — while we will not take the
  lead on this task, we will provide specific guidance and feedback,
  and potentially adjust `sftrack` to match the needs of each package
  involved at this stage.
* **Submission to rOpenSci** [month 5–6]: In the last two months, we
  will go one step further and actually prepare `sftrack` for
  rOpenSci, which will coincide with the stable public API of version
  1.0. rOpenSci emphasizes (and basically enforces) a package's
  quality, fit, documentation, and clarity. `sftrack` would fit in the
  special category "geospatial data". Becoming the first official
  rOpenSci tracking package (none of the 58 existing tracking packages
  are currently on rOpenSci) would give the package extra visibility,
  and guarantee its overall usefulness and usability.


## Other aspects
<!--
Covering non-technical activities like on-going publicity, paper preparation, discussion groups etc. that might be required to facilitate successful delivery of the project.

 - [ ] Announcement post
 - [ ] Delivery blog post
 - [ ] Twitter
 - [ ] UseR!
 - [ ] ISC meetings
-->

The work on `sftrack` will happen completely in the open. We will keep
communicating our progress, directly on Twitter as well as with more
detailed blog posts on https://mablab.org/. We will watch for
feedback, notably through the GitHub repository, which will collect
use cases, bug issues and suggestions for enhancements. We have
already successfully presented our work on `sftrack` at the 2020
Moving2Gather conference (held in Rennes, France, in March 2020), and
will consider other venues once the situation with COVID-19 allows us
to travel normally. For instance, we have submitted an abstract for
the useR! 2020 conference in July 2020 (St. Louis, MO, USA).
